### ISSUE TITLE
No such dataset implementation None

### ISSUE THREAD

**Issue by aquorio15** [esalesky/visrep#3]
Hi, I have been trying to implement the code on MTTT dataset as given in the paper. But while loading the data during fairseq train, I am getting the following error 'No such dataset implementation None' probably while loading the data.
![Screenshot from 2022-08-02 15-57-28](https://user-images.githubusercontent.com/91369740/182354135-9ef146e4-da68-42c3-8d34-94c6c6bc4e78.png)
Any kind of help would be greatly appreciated

Command line for traing in case i am doing something wrong
CUDA_VISIBLE_DEVICES=0 fairseq-train data-bin/MMMT.tokenized.en-tr --task visual_text --source-lang en --target-lang tr --target-dict dict.tr.txt  --arch visual_text_transformer --image-window 15 --image-stride 10 --image-font-path fairseq/data/visual/fonts/NotoSans-Regular.ttf --image-embed-normalize --image-embed-type 1layer  --share-decoder-input-output-embed     --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0     --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000     --dropout 0.3 --weight-decay 0.0001     --criterion label_smoothed_cross_entropy --label-smoothing 0.1     --max-tokens 4096   --max-epoch 50

**Comment by esalesky** [comment]
My guess is that you need to set the parameter `--dataset_impl` in your training command. 

In the first line in the screenshot, `dataset_impl=None`. If you're using binarized data, you'll want to set this to `mmap`, and if you're using raw data (not binarized, images computed when internal dataset representation constructed, which is what I typically did for MTTT because it is relatively small), you can set this to `raw`. 

If you still see an issue, please comment again and I'll do my best to help, and if that works, feel free to close!

**Comment by aquorio15** [comment]
Hi thank you for the reply
It is working now, just a small question did you try this model with very small dataset let's say (around 10000 sentence pair)

Also how did you evaluate your trained model.

**Comment by esalesky** [comment]
Great, glad to hear! 

No, I did not try datasets smaller than MTTT. You may want to try adapting a model trained on more data. 

We evaluated using BLEU as computed by [sacrebleu](https://github.com/mjpost/sacrebleu), after first [removing sentencepiece](https://github.com/google/sentencepiece#decode-sentence-piecesids-into-raw-text) segmentation.
